# Generated by django-oauth-toolkit

import oauth2_provider.models
from django.db import migrations
from django.db.models import F
from oauth2_provider.settings import oauth2_settings


def forwards_func(apps, schema_editor):
    """
    Replace every plain text access token with its already computed SHA-256
    checksum so that existing tokens keep working after the migration.
    """
    AccessToken = apps.get_model(oauth2_settings.ACCESS_TOKEN_MODEL)
    AccessToken._default_manager.update(token=F("token_checksum"))


def reverse_func(apps, schema_editor):
    """
    Restore the checksum column from the hashed token values.
    The original plain text tokens cannot be recovered.
    """
    AccessToken = apps.get_model(oauth2_settings.ACCESS_TOKEN_MODEL)
    AccessToken._default_manager.update(token_checksum=F("token"))


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0014_alter_help_text"),
        migrations.swappable_dependency(oauth2_settings.ACCESS_TOKEN_MODEL),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name="accesstoken",
            name="token_checksum",
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="token",
            field=oauth2_provider.models.TokenHashField(max_length=64, unique=True),
        ),
    ]
